[build]
  publish = "dist"
  command = "pnpm build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://agenda-backend-137q.onrender.com/api/:splat"
  status = 200
  force = true
